### ISSUE TITLE
arm64-v8a

### ISSUE THREAD

**Issue by ANURAGX** [adynathos/AugmentedUnreality#10]
Hi Adynathos,
First of all I wanted to thank you for this wonderful work of yours.

I need just some help to compiling libs for arm64-v8a architecture, I tried by myself but failed.
I went through the opencv repository also, I could compile opencv libs but couldn't compile the aruco module as it's not available in opencv.

Could you please tell the exact version of openCV you are using, so that I can add the openCV libs for arm64-v8a platform.

**I know this is not an issue, but there is no other way to contact you and get help from you.**
Thanking you in anticipation.

Regards.

**Comment by adynathos** [comment]
Hello
Thank you for using the plugin.

The procedure of building OpenCV for the plugin is described [here](https://github.com/adynathos/AugmentedUnreality/tree/master/ThirdParty/opencv) (there is also a link to OpenCV-contrib repository containing the additional modules like `aruco`)

Following that procedure, you should be able to compile OpenCV with the right modules and automatically copy the needed files to the plugin.

To build for `arm64-v8a`, maybe modify the [CMake settings for android](https://github.com/adynathos/AugmentedUnreality/blob/master/ThirdParty/opencv/cmake_settings/android.cmake) by adding:
```
set(ANDROID_ABI "arm64-v8a" CACHE STRING "")
```

**Comment by ANURAGX** [comment]
Really thanks mate.

**Comment by ANURAGX** [comment]
I m using your work as a base for creating plugin using artoolkit 6.

Right now I m able to load a dynamic image on the fly and able to get it
detected.

**Comment by adynathos** [comment]
I tried ARToolkit when I started this plugin, but OpenCV was easier to work with. Maybe that changed now.

But as far as I remember ARToolkit also works with fiducial markers?

It would be better to do it without markers, for example with the <a href="https://github.com/ethz-asl/rovio">ROVIO</a> library, using vision and the accelerometer.

On the other hand, maybe our efforts on AR plugins are futile, because of <a href="https://www.blog.google/products/google-vr/arcore-augmented-reality-android-scale/">ARCore</a> - AR integrated into Android.
<a href="https://developers.google.com/ar/develop/unreal/getting-started">And it should also work with Unreal.<a/>

**Comment by ANURAGX** [comment]
Thanks a lot for this information.
I didn't know about ARCore.
