### ISSUE TITLE
no such file or directory: armeabi-v7a/libopencv_augmented_unreality.a

### ISSUE THREAD

**Issue by signupdemo** [adynathos/AugmentedUnreality#22]
ok.. so I followed some fixes mentioned earlier, but Im stuck at this error, and cant seems to find these files:

clang++.exe: error: no such file or directory:...AugmentedUnrealityEx/Plugins/AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_augmented_unreality.a'
UATHelper: Packaging (Android (ASTC)): clang++.exe: error: no such file or directory:
clang++.exe: error: no such file or directory:'...AugmentedUnrealityEx/Plugins/AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_aruco.a'
UATHelper: Packaging (Android (ASTC)): ERROR: UBT ERROR: Failed to produce item: ....AugmentedUnrealityEx\Binaries\Android\AugmentedUnrealityEx-armv7-es2.so

Would really appreciate if anybody can help...

**Comment by adynathos** [comment]
The directory where OpenCV puts it libraries changed, it is fixed in https://github.com/adynathos/AugmentedUnreality/commit/032a0b8ab08bf4ece304145be6c3634c00cd0250

Here is the build <a href="https://github.com/adynathos/AugmentedUnreality/releases/tag/1.2.04">1.2.04</a> for UE 4.19 and OpenCV 3.4.1
It contains the OpenCV libraries for Windows and Android.

**Comment by signupdemo** [comment]
Thanks... I dont have 4.19 yet, but I copied the missing android libraries and it worked :)
